# # Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

# version: '3.4'

# networks:
#  polyclinic-dev:
#    driver: bridge

# services:
#   polyclinic:
#     build:
#       context: .
#       dockerfile: Polyclinic/Dockerfile
#     ports:
#       - 5157:5157 
#     networks:
#       - polyclinic-dev
#     depends_on:
#       - postgres_db

#   postgres_db:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_USER: postrges
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: pasha
#    ports:
#      - 5432:5432 
#    networks:
#      - polyclinic-dev
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

# volumes:
#  postgres-data:

# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  polyclinic:
    image: polyclinic
    build:
      context: .
      dockerfile: Polyclinic/Dockerfile
    ports:
      - 5150:5150
    depends_on:
      - "postgresdb"
    networks:
      - dockerapi-dev

  postgresdb:
    image: postgres:latest
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Polyclinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pasha
    ports:
      - 5432:5432
    networks:
      - dockerapi-dev
volumes:
  db_volume: